name: JohnDroid-Official-Engine
on: [workflow_dispatch]

jobs:
  sync-and-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout JohnDroid Repo
        uses: actions/checkout@v4

      - name: Maximize Disk Space
        uses: easimon/maximize-build-disk-space@main
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Setup Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync AOSP 16
        run: |
          export PATH=$HOME/bin:$PATH
          repo init -u https://android.googlesource.com/platform/manifest -b android-latest-release --depth=1
          mkdir -p .repo/local_manifests
          cp $GITHUB_WORKSPACE/default.xml .repo/local_manifests/johndroid.xml
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle --optimized-fetch

      - name: Apply Manual Mods
        run: |
          if [ -d "$GITHUB_WORKSPACE/my_mods" ]; then
            cp -rv $GITHUB_WORKSPACE/my_mods/* .
          else
            echo "No mods folder found."
          fi

      - name: T7100 Compatibility Fix
        run: |
          find build/make/core/combo/arch/x86_64/ -name "x86_64.mk" -exec sed -i 's/ARCH_X86_HAVE_SSE4_2 := true/ARCH_X86_HAVE_SSE4_2 := false/g' {} +
          find build/make/core/combo/arch/x86_64/ -name "x86_64.mk" -exec sed -i 's/ARCH_X86_HAVE_SSE4_1 := true/ARCH_X86_HAVE_SSE4_1 := false/g' {} +
          echo "PRODUCT_PROPERTY_OVERRIDES += ro.config.low_ram=true" >> build/make/target/product/base_system.mk
